
name : Update News Section

on:

    workflow_dispatch:

    pull_request:

        paths :
            
            -   'News/**'

    push:
        
        paths :
            
            -   'News/**'


                    
concurrency:

    cancel-in-progress : true
    group : news


jobs :
    Build :

        runs-on : ubuntu-latest

        steps :

            -   name : Checkout
                uses : actions/checkout@v3
                if : ${{ github.event_name != 'pull_request' }}
                
            -   name : Checkout
                uses : actions/checkout@v3
                if : ${{ github.event_name == 'pull_request' }}

                with :
                    repository : ${{ github.event.pull_request.head.repo.full_name }}
                    ref : ${{ github.event.pull_request.head.ref }}


            -   name : Run News Builder
                uses : MarkedDown/News@1.0.0
                with :
                    
                    config : .github/.News.yml
                
            -   name : Commit Changes
                uses : EndBug/add-and-commit@v9
                with :
                    
                    default_author : github_actor
                    message : Updated News Section
                    add : profile/README.md
